### PR TITLE
fedora: add scafacos

### PR DESCRIPTION
**Pull request by junghans**
For https://github.com/espressopp/espressopp/pull/420

### CODE REVIEW

**Comment by junghans** [comment]
@rhalver any ideas why this fails?
```
/bin/sh ../libtool  --tag=FC   --mode=compile mpif90 -DHAVE_FCONFIG_H -I. -I..    -I../../.. -g -O2 -ffree-form -ffree-line-length-none -fopenmp -c -o module_interaction_specific_types_XYZQ.pp.lo -cpp module_interaction_specific_types_XYZQ.pp.f90
libtool: compile:  mpif90 -DHAVE_FCONFIG_H -I. -I.. -I../../.. -g -O2 -ffree-form -ffree-line-length-none -fopenmp -c -cpp module_interaction_specific_types_XYZQ.pp.f90 -o module_interaction_specific_types_XYZQ.pp.o
module_interaction_specific_types_XYZQ.pp.f90:151:30:
  150 |         call MPI_GET_ADDRESS( dummy_particle_data, address(0), ierr )
      |                              2
  151 |         call MPI_GET_ADDRESS( dummy_particle_data%q, address(1), ierr )
      |                              1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/TYPE(t_particle_data)).
```

**Comment by xzhh** [comment]
We should add --enable-shared for ./configure. Otherwise scafacos libraries will not be read in epp
I am unsure whether it is still necessary to manually specify the location to fftw (e.g. --with-fftw3=$EBROOTFFTW) but i do it every time in compilation.

**Comment by xzhh** [comment]
> @rhalver any ideas why this fails?
> 
> ```
> /bin/sh ../libtool  --tag=FC   --mode=compile mpif90 -DHAVE_FCONFIG_H -I. -I..    -I../../.. -g -O2 -ffree-form -ffree-line-length-none -fopenmp -c -o module_interaction_specific_types_XYZQ.pp.lo -cpp module_interaction_specific_types_XYZQ.pp.f90
> libtool: compile:  mpif90 -DHAVE_FCONFIG_H -I. -I.. -I../../.. -g -O2 -ffree-form -ffree-line-length-none -fopenmp -c -cpp module_interaction_specific_types_XYZQ.pp.f90 -o module_interaction_specific_types_XYZQ.pp.o
> module_interaction_specific_types_XYZQ.pp.f90:151:30:
>   150 |         call MPI_GET_ADDRESS( dummy_particle_data, address(0), ierr )
>       |                              2
>   151 |         call MPI_GET_ADDRESS( dummy_particle_data%q, address(1), ierr )
>       |                              1
> Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/TYPE(t_particle_data)).
> ```

Usually I disabled fortran compilation

**Comment by junghans** [comment]
@xzhh thanks let's see if it works now.

**Comment by junghans** [comment]
Ok, now I am stuck at:
```
/usr/bin/ld: .libs/libfcs_memd_la-communication.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: multiple definition of `memd'; .libs/libfcs_memd_la-helper_functions.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: first defined here
/usr/bin/ld: .libs/libfcs_memd_la-getter_setter.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: multiple definition of `memd'; .libs/libfcs_memd_la-helper_functions.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: first defined here
/usr/bin/ld: .libs/libfcs_memd_la-init.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: multiple definition of `memd'; .libs/libfcs_memd_la-helper_functions.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: first defined here
/usr/bin/ld: .libs/libfcs_memd_la-interpolate.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: multiple definition of `memd'; .libs/libfcs_memd_la-helper_functions.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: first defined here
/usr/bin/ld: .libs/libfcs_memd_la-initial_solution.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: multiple definition of `memd'; .libs/libfcs_memd_la-helper_functions.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: first defined here
/usr/bin/ld: .libs/libfcs_memd_la-forces.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: multiple definition of `memd'; .libs/libfcs_memd_la-helper_functions.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: first defined here
/usr/bin/ld: .libs/libfcs_memd_la-run.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: multiple definition of `memd'; .libs/libfcs_memd_la-helper_functions.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: first defined here
/usr/bin/ld: .libs/libfcs_memd_la-observables.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: multiple definition of `memd'; .libs/libfcs_memd_la-helper_functions.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: first defined here
```

**Comment by xzhh** [comment]
> Ok, now I am stuck at:
> 
> ```
> /usr/bin/ld: .libs/libfcs_memd_la-communication.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: multiple definition of `memd'; .libs/libfcs_memd_la-helper_functions.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: first defined here
> /usr/bin/ld: .libs/libfcs_memd_la-getter_setter.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: multiple definition of `memd'; .libs/libfcs_memd_la-helper_functions.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: first defined here
> /usr/bin/ld: .libs/libfcs_memd_la-init.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: multiple definition of `memd'; .libs/libfcs_memd_la-helper_functions.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: first defined here
> /usr/bin/ld: .libs/libfcs_memd_la-interpolate.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: multiple definition of `memd'; .libs/libfcs_memd_la-helper_functions.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: first defined here
> /usr/bin/ld: .libs/libfcs_memd_la-initial_solution.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: multiple definition of `memd'; .libs/libfcs_memd_la-helper_functions.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: first defined here
> /usr/bin/ld: .libs/libfcs_memd_la-forces.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: multiple definition of `memd'; .libs/libfcs_memd_la-helper_functions.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: first defined here
> /usr/bin/ld: .libs/libfcs_memd_la-run.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: multiple definition of `memd'; .libs/libfcs_memd_la-helper_functions.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: first defined here
> /usr/bin/ld: .libs/libfcs_memd_la-observables.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: multiple definition of `memd'; .libs/libfcs_memd_la-helper_functions.o:/home/espressopp/scafacos/lib/memd/data_types.h:172: first defined here
> ```

Disable it if envs do not support, using --disable-fcs-[SOLVER] (e.g. SOLVER=memd). In fact, it is not meaningful to load all methods since some require not supported PBCs and some may need customized fft libs. Usually I only do, instead, --enable-fcs-solvers=direct,ewald,p3m,wolf and I would also suggest to load only selected methods and leave a message to users in case they need to customize.

**Comment by junghans** [comment]
@xzhh please review!

**Comment by xzhh** [comment]
> @xzhh please review!

ah, so one can co-build static and dynamic libraries. Not aware before

**Pull request merged**
