### PR TITLE
remove pre-installed python packages and rely on requirements.txt

### LINKED ISSUE #49: Drop "pip3 install pyh5md"
I don't think we need `pip3 install pyh5md` anymore, so should we drop it?

### PR DESCRIPTION
**Pull request by XzzX**
Remove preinstalled python dependencies and rely on `pip install -r requirements.txt`.

closes #49

### CODE REVIEW

**Comment by XzzX** [comment]
@junghans Any ideas for the `mpi` specific packages? How to generalize the installation process?

**Comment by junghans** [comment]
Wouldn't we first add `pip install -r requirements.txt` to the other CI?

**Comment by XzzX** [comment]
> Wouldn't we first add `pip install -r requirements.txt` to the other CI?

https://github.com/espressopp/espressopp/pull/377

**Comment by junghans** [comment]
After thinking about it, I would suggest to keep MPI related package from the distros to avoid incompatibilities.

**Comment by XzzX** [comment]
I agree, `pip` will recognize them and not reinstall them.

**Pull request closed without merging**
